# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wf-peEmny5B1K5ytDbNZTbhr1v6Noyb3
"""

lst = [3,7,2]
histo =[]
for num in lst:
  num1 = "*" * num
  histo.append(num1)

print(histo)

lst1 = ['a','b','c']
lst2 = ['x', 'y', 'z']
lst_res =[]

for (i,j) in zip(lst1, lst2[::-1]):
    ch = i+j
    lst_res.append(ch)

print(lst_res)